import './globals.css'
import { Inter, Roboto } from '@next/font/google'

import Navbar from './components/navbar'
import Menu from './components/menu'
import Footer from './components/footer'

const inter = Inter(
  {
    subsets: ['latin'],
    variable: '--font-inter',
  }
)

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  style: 'normal',
  display: 'swap',
  variable: '--font-roboto',
})

export const metadata = {
  title: 'blog-app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <Navbar params={<Menu />} />
        {children}
        <Footer />
      </body>
    </html>
  )
}
